const MyEditorActionsConstants = {
  UPLOAD_ACTION: 'UPLOAD_ACTION',
  DONE_ACTION: 'DONE_ACTION',
  EDIT_TEXT_ACTION: 'EDIT_TEXT_ACTION',
  CHANGE_OPTIONS_ACTION: 'CHANGE_OPTIONS_ACTION'
};

export { MyEditorActionsConstants };
