const MyEditorActionsConstants = {
  UPLOAD_ACTION: 'UPLOAD_ACTION',
  DONE_ACTION: 'DONE_ACTION',
  EDIT_TEXT_ACTION: 'EDIT_TEXT_ACTION',
  SHOW_OVERLAY_ACTION: 'SHOW_OVERLAY_ACTION'
};

export { MyEditorActionsConstants };
